# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          # Opcional pero buena práctica: cachear las dependencias por carpeta
          cache-dependency-path: micarpeta-con-el-proyecto/package-lock.json

      - name: Install dependencies
        # AQUÍ ESTÁ EL CAMBIO
        working-directory: ./micarpeta-con-el-proyecto 
        run: npm install

      - name: Build your site
        # AQUÍ ESTÁ EL CAMBIO
        working-directory: ./micarpeta-con-el-proyecto
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # IMPORTANTE: La ruta al directorio 'dist' ahora está dentro de tu carpeta
          path: ./micarpeta-con-el-proyecto/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
